# Secondary Pulp3 instance
version: '3.8'

services:
  postgres-secondary:
    image: "docker.io/library/postgres:13"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pulp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulp_secondary
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
      - "pg_data_secondary:/var/lib/postgresql/data"
    restart: always
    healthcheck:
      test: pg_isready -U pulp -d pulp_secondary
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  redis-secondary:
    image: "docker.io/library/redis:latest"
    volumes:
      - "redis_data_secondary:/data"
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  migration-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    depends_on:
      postgres-secondary:
        condition: service_healthy
    command: pulpcore-manager migrate --noinput
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    environment:
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    networks:
      - pulp-net

  signing-key-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    command: sh -c "add_signing_service.sh"
    depends_on:
      postgres-secondary:
        condition: service_healthy
      migration-secondary: 
        condition: service_completed_successfully
    environment:
      PULP_SIGNING_KEY_FINGERPRINT: ''
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    networks:
      - pulp-net

  init-password-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    command: set_init_password.sh
    depends_on:
      postgres-secondary:
        condition: service_healthy
    environment:
      PULP_DEFAULT_ADMIN_PASSWORD: password
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    networks:
      - pulp-net

  pulp-web-secondary:
    image: "pulp/pulp-web:3.49.1"
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      pulp-api-secondary:
        condition: service_healthy
      pulp-content-secondary:
        condition: service_healthy
    ports:
      - "8001:8080"
    hostname: pulp-web-secondary
    user: root
    volumes:
      - "../../assets/nginx-conf/nginx-secondary.conf:/etc/nginx/nginx.conf:Z"
    restart: always
    networks:
      - pulp-net

  pulp-api-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
      replicas: 2
    command: ['pulp-api']
    depends_on:
      redis-secondary:
        condition: service_healthy
      postgres-secondary:
        condition: service_healthy
      migration-secondary:
        condition: service_completed_successfully
      init-password-secondary:
        condition: service_completed_successfully
      signing-key-secondary:
        condition: service_completed_successfully
    hostname: pulp-api-secondary
    user: pulp
    environment:
      PULP_SETTINGS: /etc/pulp/settings.py
      PULP_ALLOWED_HOSTS: '["*"]'
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    restart: always
    healthcheck:
      test: readyz.py /pulp/api/v3/status/
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  pulp-content-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
      replicas: 2
    command: ['pulp-content']
    depends_on:
      redis-secondary:
        condition: service_healthy
      postgres-secondary:
        condition: service_healthy
      migration-secondary:
        condition: service_completed_successfully
    hostname: pulp-content-secondary
    user: pulp
    environment:
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    restart: always
    healthcheck:
      test: readyz.py /pulp/content/
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  pulp-worker-secondary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
        replicas: 2
    command: ['pulp-worker']
    depends_on:
      redis-secondary:
        condition: service_healthy
      postgres-secondary:
        condition: service_healthy
      migration-secondary:
        condition: service_completed_successfully
    user: pulp
    environment:
      POSTGRES_HOST: postgres-secondary
      REDIS_HOST: redis-secondary
    volumes:
      - "../../assets/settings_secondary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_secondary:/var/lib/pulp"
    restart: always
    networks:
      - pulp-net

volumes:
  pulp_secondary:
    name: pulp_secondary_local
  pg_data_secondary:
    name: pg_data_secondary_local
  redis_data_secondary:
    name: redis_data_secondary_local

networks:
  pulp-net:
    external: true