# Primary Pulp3 instance
version: '3.8'

services:
  postgres-primary:
    image: "docker.io/library/postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pulp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulp_primary
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
      - "pg_data_primary:/var/lib/postgresql/data"
    restart: always
    healthcheck:
      test: pg_isready -U pulp -d pulp_primary
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  redis-primary:
    image: "docker.io/library/redis:latest"
    volumes:
      - "redis_data_primary:/data"
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  migration-primary:
    image: "pulp/pulp-minimal:3.49.1"
    depends_on:
      postgres-primary:
        condition: service_healthy
    command: pulpcore-manager migrate --noinput
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    environment:
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    networks:
      - pulp-net

  signing-key-primary:
    image: "pulp/pulp-minimal:3.49.1"
    command: sh -c "add_signing_service.sh"
    depends_on:
      postgres-primary:
        condition: service_healthy
      migration-primary: 
        condition: service_completed_successfully
    environment:
      PULP_SIGNING_KEY_FINGERPRINT: ''
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    networks:
      - pulp-net

  init-password-primary:
    image: "pulp/pulp-minimal:3.49.1"
    command: set_init_password.sh
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      PULP_DEFAULT_ADMIN_PASSWORD: password
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    networks:
      - pulp-net

  pulp-web-primary:
    image: "pulp/pulp-web:3.49.1"
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      pulp-api-primary:
        condition: service_healthy
      pulp-content-primary:
        condition: service_healthy
    ports:
      - "8000:8080"
    hostname: pulp-web-primary
    user: root
    volumes:
      - "../../assets/nginx-conf/nginx-primary.conf:/etc/nginx/nginx.conf:Z"
    restart: always
    networks:
      - pulp-net

  pulp-api-primary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
      replicas: 2
    command: ['pulp-api']
    depends_on:
      redis-primary:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
      migration-primary:
        condition: service_completed_successfully
      init-password-primary:
        condition: service_completed_successfully
      signing-key-primary:
        condition: service_completed_successfully
    hostname: pulp-api-primary
    user: pulp
    environment:
      PULP_SETTINGS: /etc/pulp/settings.py
      PULP_ALLOWED_HOSTS: '["*"]'
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    restart: always
    healthcheck:
      test: readyz.py /pulp/api/v3/status/
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  pulp-content-primary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
      replicas: 2
    command: ['pulp-content']
    depends_on:
      redis-primary:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
      migration-primary:
        condition: service_completed_successfully
    hostname: pulp-content-primary
    user: pulp
    environment:
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    restart: always
    healthcheck:
      test: readyz.py /pulp/content/
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulp-net

  pulp-worker-primary:
    image: "pulp/pulp-minimal:3.49.1"
    deploy:
        replicas: 2
    command: ['pulp-worker']
    depends_on:
      redis-primary:
        condition: service_healthy
      postgres-primary:
        condition: service_healthy
      migration-primary:
        condition: service_completed_successfully
    user: pulp
    environment:
      POSTGRES_HOST: postgres-primary
      REDIS_HOST: redis-primary
    volumes:
      - "../../assets/settings_primary.py:/etc/pulp/settings.py:z"
      - "../../assets/certs:/etc/pulp/certs:z"
      - "../../assets/keys:/etc/pulp/keys:z"
      - "pulp_primary:/var/lib/pulp"
    restart: always
    networks:
      - pulp-net

volumes:
  pulp_primary:
    name: pulp_primary_local
  pg_data_primary:
    name: pg_data_primary_local
  redis_data_primary:
    name: redis_data_primary_local

networks:
  pulp-net:
    external: true